### PR TITLE
Kinetic fixes

### LINKED ISSUE #3: make available for kinetic
`catkin build` throws an error:
```
Errors     << canopen_test_utils:make /u/robot/git/care-o-bot/logs/canopen_test_utils/build.make.000.log          
/u/robot/git/care-o-bot/src/canopen_test_utils/src/elmo_console.cpp:2:35: fatal error: canopen_master/master.h: No such file or directory
```
`master.h` is not available under kinetic anymore

### PR DESCRIPTION
**Pull request by mathias-luedtke**
@HannesBachter: please test
closes #3

### CODE REVIEW

**Review by floweisshardt — APPROVED** [review]
works on ubuntu 16.04/kinetic
